name: Publish

on:
  push:
    tags:
      - "[0-9].[0-9].[0-9]"

jobs:
  libkt:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Java
        uses: actions/setup-java@v2.1.0
        with:
          java-version: 1.14

      - name: Cache
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/build.gradle.kts') }}

      - name: Publish
        run: ./gradlew publish -Pversion=$(echo ${{ github.ref }} | sed s#refs/tags/##)
        working-directory: libkt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
