name: Verify

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  libkt:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Java
        uses: actions/setup-java@v2.1.0
        with:
          java-version: 1.14

      - name: Cache
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/build.gradle.kts') }}

      - name: Build
        run: ./gradlew build
        working-directory: libkt
